# ================================================
# === boilerplate to get a bootable deployment ===
# ================================================
config:
  encryptionKey: '000000000'
  jwtSecret: '000000000'

  licenseKey: "EXPIRED-LICENSE-KEY-TRIAL"

image:
  tag: 'latest'

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 1000m
    memory: 4096Mi

workflows:
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi

env:
  NUM_WORKERS: '1'
  # NODE_DEBUG: 'module'

ingress:
  kubernetes.io/ingress.class: nginx
  hosts:
  - host: retool.example.com
    paths:
      - path: /

livenessProbe:
  timeoutSeconds: 60
  periodSeconds: 2
  failureThreshold: 60
readinessProbe:
  timeoutSeconds: 30
  periodSeconds: 5

replicaCount: 1

persistentVolumeClaim:
  size: '3Gi'
# ================================================

# === New telemetry stuff ===
telemetry:
  enabled: true
  image:
    repository: 'tryretool/telemetry'
    # tag:
  sendToRetool:
    enabled: true
  customVectorConfig:
    foo: bar
  customGrafanaAgentConfig: |
    // wee woo custom text
