remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - retool=https://charts.retool.com
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 300s
check-version-increment: true
validate-maintainers: false
debug: true
