apiVersion: v2
name: retool
description: A Helm chart for Kubernetes
type: application
version: 4.5.0
maintainers:
  - name: Retool Engineering
    email: engineering+helm@retool.com
dependencies:
  - name: postgresql
    version: 10.9.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
